/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BAB6.Abstract;

/**
 *
 * @author ASUS
 */
public class GUI_JadwalBadminton extends javax.swing.JFrame {

    /**
     * Creates new form GUI_JadwalBadminton
     */
    public GUI_JadwalBadminton() {
        initComponents();
    }
    public void batal() {
    txtTanggal.setText("");
    txtJam.setText("");
    txtLapangan.setText("");
    txtPemain1.setText(""); 
    txtPemain2.setText(""); 
    txtJadwal.setText("");
    
    // Cara manual buat matiin pilihan radio button
    btnGanda.setSelected(false);
    btnTunggal.setSelected(false);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        txtTanggal = new javax.swing.JTextField();
        txtJam = new javax.swing.JTextField();
        txtLapangan = new javax.swing.JTextField();
        txtPemain1 = new javax.swing.JTextField();
        txtPemain2 = new javax.swing.JTextField();
        btnGanda = new javax.swing.JRadioButton();
        btnTunggal = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtJadwal = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("SISTEM JADWAL BADMINTON");

        jLabel2.setText("Tanggal");

        jLabel3.setText("Jam");

        jLabel4.setText("Lapangan");

        jLabel5.setText("Kategori");

        jLabel6.setText("Pemain 1");

        jLabel7.setText("Pemain 2");

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        txtPemain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPemain1ActionPerformed(evt);
            }
        });

        txtPemain2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPemain2ActionPerformed(evt);
            }
        });

        btnGanda.setText("Ganda");
        btnGanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGandaActionPerformed(evt);
            }
        });

        btnTunggal.setText("Tunggal");
        btnTunggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTunggalActionPerformed(evt);
            }
        });

        txtJadwal.setColumns(20);
        txtJadwal.setRows(5);
        jScrollPane1.setViewportView(txtJadwal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSimpan)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnGanda)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnTunggal))
                                    .addComponent(txtTanggal)
                                    .addComponent(txtJam)
                                    .addComponent(txtLapangan)
                                    .addComponent(txtPemain1)
                                    .addComponent(txtPemain2))))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBatal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnKeluar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtLapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(btnGanda)
                            .addComponent(btnTunggal))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPemain1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtPemain2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBatal)
                        .addComponent(btnKeluar)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String tanggal = txtTanggal.getText().trim();
        String jam = txtJam.getText().trim();
        String lapangan = txtLapangan.getText().trim();
        String pemain1 = txtPemain1.getText().trim();
        String pemain2 = txtPemain2.getText().trim();

        String kategori = "";
        if (btnTunggal.isSelected()) {
            kategori = "TUNGGAL";
        } else if (btnGanda.isSelected()) {
            kategori = "GANDA";
        }

    // Validasi
        if (tanggal.isEmpty() || jam.isEmpty() || lapangan.isEmpty() || pemain1.isEmpty() || kategori.isEmpty()) {
            txtJadwal.append("Data belum lengkap!\n\n");
            return;
        }

        if (kategori.equals("GANDA") && pemain2.isEmpty()) {
            txtJadwal.append("Pemain 2 wajib diisi untuk ganda!\n\n");
            return;
        }

        String hasil = "===== DATA BOOKING =====\n"
                    + "Tanggal   : " + tanggal + "\n"
                    + "Jam       : " + jam + "\n"
                    + "Lapangan  : " + lapangan + "\n"
                    + "Kategori  : " + kategori + "\n"
                    + "Pemain 1  : " + pemain1 + "\n";

        if (kategori.equals("GANDA")) {
            hasil += "Pemain 2  : " + pemain2 + "\n";
        }

        hasil += "========================\n\n";

        txtJadwal.append(hasil);

    // Auto reset ringan setelah simpan
        txtPemain1.setText("");
        txtPemain2.setText("");
        txtPemain1.requestFocus();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtPemain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPemain1ActionPerformed
        txtPemain2.requestFocus(); // pindah ke pemain 2    
    }//GEN-LAST:event_txtPemain1ActionPerformed

    private void txtPemain2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPemain2ActionPerformed
        btnSimpan.requestFocus(); // langsung ke tombol simpan
    }//GEN-LAST:event_txtPemain2ActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        txtTanggal.setText("");
        txtJam.setText("");
        txtLapangan.setText("");
        txtPemain1.setText("");
        txtPemain2.setText("");

        btnTunggal.setSelected(false);
        btnGanda.setSelected(false);

        txtPemain2.setEnabled(true);

        txtJadwal.append("❌ Input dibatalkan\n\n");

        txtTanggal.requestFocus();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        txtJadwal.append("Aplikasi ditutup...\n");
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnGandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGandaActionPerformed
        txtPemain2.setEnabled(true);
        txtPemain2.setText(""); // kosong juga
    }//GEN-LAST:event_btnGandaActionPerformed

    private void btnTunggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTunggalActionPerformed
        txtPemain2.setEnabled(false);
        txtPemain2.setText(""); // kosong, bukan "Pemain 2"
    }//GEN-LAST:event_btnTunggalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_JadwalBadminton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_JadwalBadminton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_JadwalBadminton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_JadwalBadminton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_JadwalBadminton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JRadioButton btnGanda;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JRadioButton btnTunggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtJadwal;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtLapangan;
    private javax.swing.JTextField txtPemain1;
    private javax.swing.JTextField txtPemain2;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
